In [1]:
import numpy as np

In [2]:
matrix1 = [[1,2,3,4],[1,2,3,4]]

In [3]:
matrix2 = [[1,2],[3,4],[1,2],[3,4]]

In [4]:
matrix1 = np.array(matrix1)

In [5]:
matrix2 = np.array(matrix2)

In [6]:
print(matrix1.shape , matrix2.shape)

(2, 4) (4, 2)


In [7]:
result = np.dot(matrix1,matrix2)

In [8]:
print(result.shape)

(2, 2)


In [11]:
print(matrix2.dot(matrix1))

[[ 3  6  9 12]
 [ 7 14 21 28]
 [ 3  6  9 12]
 [ 7 14 21 28]]


In [47]:
parameters = np.random.rand(3,3,32)
X = np.random.rand(15,256,3)
stride = 1

In [48]:
print(parameters.shape)
print(parameters.transpose(1,0,2).shape)
print(X.shape)

(3, 3, 32)
(3, 3, 32)
(15, 256, 3)


In [49]:
np.dot(parameters , X)

ValueError: shapes (3,3,32) and (15,256,3) not aligned: 32 (dim 2) != 256 (dim 1)

In [50]:
res = []
for filtre_index in range(parameters.shape[2]) :
    res.append(np.dot(X[0] , parameters[:,:,filtre_index])) 
#print(np.array(res).shape)


In [51]:
size = ((X.shape[1] - 3) // stride) + 1

In [52]:
print(size)

254


In [54]:
k_size = 3
output = np.array([ X[ : , i : i + k_size, :].reshape(X.shape[0],-1) @ parameters.reshape(-1,parameters.shape[2]) for i in range(0,size,stride)])
print(output.shape)
print(output.transpose(1,0,2).shape)

(254, 15, 32)
(15, 254, 32)


In [40]:
parameters.reshape(-1, 32).shape

(9, 32)

In [41]:
parameters.reshape(3, -1).shape

(3, 96)

In [58]:
output = np.array([ np.max(X[ : , i : i + k_size, :],axis=1) for i in range(0,size,stride)])
print(output.transpose(1,0,2).shape)

(15, 254, 3)
